import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LocalFont from 'next/font/local'
import '@/styles/globals.css';
import Providers from "@/components/providers";
import {cn} from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
// const unifont = LocalFont({
//   src: "../public/fonts/unifont_jp-15.1.04.otf",
//   variable: "--font-unifont",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
